# Generated by Django 6.0.3 on 2026-03-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = []
