# Generated by Django 6.0.3 on 2026-03-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_force_init"),
        ("books", "0003_add_genre"),
    ]

    operations = []
