# Generated by Django 6.0.3 on 2026-03-28 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_publisher_review_store_book_publisher_book_reviews_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="reviews",
        ),
        migrations.AddField(
            model_name="review",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="books.book",
            ),
        ),
    ]
