# Generated by Django 6.0.3 on 2026-03-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_remove_book_reviews_review_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="in_stock",
            field=models.PositiveIntegerField(default=7),
        ),
    ]
