# Generated by Django 6.0.3 on 2026-03-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_book_in_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(default=7),
        ),
    ]
